################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
tools/teqser \
tools/shadeops/sci_volumes/src \
tools/ptview \
tools/procedurals/hairgen \
tools/procedurals/hairgen/kdtree \
tools/piqsl \
tools/miqser \
tools/eqsl \
tools/displays/xpm \
tools/displays/sdcWin32 \
tools/displays/sdcBMP \
tools/displays/piqsl \
tools/displays/file \
tools/displays/exr \
tools/displays/dspyutil \
tools/dbo/plane \
tools/aqsltell \
tools/aqsl \
tools/aqsis \
thirdparty/tinyxml \
thirdparty/pdiff \
thirdparty/partio/src/src/tools \
thirdparty/partio/src/src/tests \
thirdparty/partio/src/src/lib/io \
thirdparty/partio/src/src/lib/core \
thirdparty/aqiv \
prototypes/shaderVM_codegen \
prototypes/sampling \
prototypes/ri_cpp \
prototypes/piqsl_interface \
prototypes/newcore \
prototypes/newcore/ustring \
prototypes/newcore/tbb \
prototypes/newcore/scenes \
prototypes/newcore/prototype \
prototypes/newcore/experiments \
prototypes \
prototypes/float_array_view \
prototypes/binarytree \
prototypes/allocators \
libs/util/win32 \
libs/util \
libs/util/posix \
libs/tex/pointcloud \
libs/tex/maketexture \
libs/tex/io \
libs/tex/filtering \
libs/tex/buffers \
libs/slxargs \
libs/slcomp/parse \
libs/slcomp/backend \
libs/shadervm \
libs/shadervm/shaderexecenv \
libs/riutil \
libs/ri2rib \
libs/pointrender \
libs/pointrender/nondiffuse \
libs/math \
libs/core \
libs/core/texturing_old \
libs/core/raytrace \
libs/core/geometry \
libs/core/ddmanager \
libs/core/api \
libs/build_tools \
examples/procedurals/menger \
doc/guide/dev \

